mqtt:
  host: 192.168.1.1
  user: s7garage
  password: s7garage

plc:
  host: 192.168.1.2
  rack: 0
  slot: 1
  port: 102

ha:
  discovery: true
  discovery_topic: haaa
  discovery_retain: false

mqtt_base: test
retain_messages: false
update_time: 1000

devices:
  - type: light
    name: test
    mqtt: test
    state:
      plc: "DB1.DBX0.0"
    brightness:
      plc: "DB1.DBB1"
  - type: switch
    name: test2
    mqtt: test2
    state:
      plc: "DB58.X0.5"
      set_plc: "DB58.X0.7"
      rw: rw
  - type: sensor
    name: test_int
    mqtt: test_int
    state:
      plc: "DB58.I2"
      unit_of_measurement: "W"